graph:
  name: "sage-api-graph-test"
  description: "Test graph for Sage API Operator"
  platform: "ray" # or "local"
source:
  data_path: "./sage/api/operator/test/question.txt"

generator:
  method: "openai"
  model_name: "qwen-turbo-0919"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_key: "sk-b21a67cf99d14ead9d1c5bf8c2eb90ef"
  seed: 42

promptor:

sink: