name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# 并发控制：同一PR只运行最新的CI，取消之前的运行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # 公共环境变量
  CI: true
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  SILICONCLOUD_API_KEY: ${{ secrets.SILICONCLOUD_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
  ALIBABA_API_KEY: ${{ secrets.ALIBABA_API_KEY }}
  VLLM_API_KEY: ${{ secrets.VLLM_API_KEY }}
  HF_ENDPOINT: https://hf-mirror.com

jobs:
  # 快速检查：代码质量和基础测试
  quick-check:
    name: Quick Check
    runs-on: self-hosted
    timeout-minutes: 20
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        clean: true
      timeout-minutes: 5
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
      timeout-minutes: 5
      
    - name: Install Basic Dependencies
      run: |
        pip install --upgrade pip
        pip install flake8 black isort
        pip install -e packages/sage-common/ --no-deps
      timeout-minutes: 8
        
    - name: Code Quality Checks
      run: |
        echo "🔍 Running code quality checks..."
        black --check --diff packages/ || echo "⚠️ Code formatting issues found"
        isort --check-only --diff packages/ || echo "⚠️ Import sorting issues found"
        flake8 packages/ --count --select=E9,F63,F7,F82 --show-source --statistics
      timeout-minutes: 2
        
    - name: Basic Import Tests
      run: |
        echo "🧪 Testing basic imports..."
        python -c "import sage_common; print('✅ sage-common import successful')"
      timeout-minutes: 2

  # 完整测试（仅在快速检查通过后运行）
  full-test:
    name: Full Test Suite
    runs-on: self-hosted
    needs: quick-check
    timeout-minutes: 60
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        clean: true
      timeout-minutes: 8
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
      timeout-minutes: 5
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        use-mamba: true
        auto-activate-base: false
      timeout-minutes: 10
        
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
      timeout-minutes: 10
        
    - name: Install SAGE (Minimal Mode)
      run: |
        chmod +x quickstart.sh
        ./quickstart.sh --minimal
      timeout-minutes: 25
        
    - name: Run Test Suite
      run: |
        echo "🧪 Running minimal test suite..."
        python -c "import sage; print('✅ SAGE import successful, version:', sage.__version__)"
        # 可以在这里添加更多测试
      timeout-minutes: 10

  # 提醒信息（总是运行）
  info:
    name: Additional Tests Info
    runs-on: self-hosted
    if: always()
    
    steps:
    - name: Docker Integration Test Instructions
      run: |
        echo "=========================================="
        echo "📋 Additional Manual Tests Required:"
        echo ""
        echo "1. Docker Integration Test:"
        echo "   cd /home/shuhao/SAGE"
        echo "   docker build -t sage-test ."
        echo "   docker run --rm sage-test"
        echo ""
        echo "2. Full Installation Test:"
        echo "   ./quickstart.sh --standard"
        echo ""
        echo "📋 Required before merging:"
        echo "   ✅ Docker integration tests pass"
        echo "   ✅ Full installation works correctly"
        echo "=========================================="
