name: Test LLH with Pytest and Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test LLH
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Free disk space for CUDA and dependencies
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      # Remove conflicting CUDA repositories
      - name: Remove Existing CUDA Repositories
        run: sudo rm -f /etc/apt/sources.list.d/cuda* /etc/apt/sources.list.d/nvidia-*

      # Install CUDA Toolkit 11.8
      - name: Install CUDA Toolkit
        run: |
          sudo apt-get update && sudo apt-get install -y wget gnupg ca-certificates build-essential
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get install -y cuda-11-8
          nvcc --version

      # Setup Miniconda and Python environment
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          python-version: "3.11"
          activate-environment: llh
          auto-activate-base: false

      # Create and activate the environment using environment.yml
      - name: Create Environment from environment.yml
        run: |
          mamba env create -f installation/environment.yml
          conda deactivate
      # Use Deploy Key to Clone CANDY Repository
      - name: Configure SSH for Deploy Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CANDY_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Clone CANDY Repository
        run: |
          cd deps
          git clone https://github.com/intellistream/CANDY.git
      # Install `pycandy`
      - name: Install pycandy
        run: |
          cd installation
          bash candy_build.sh
          conda activate llh
          bash install_pycandy.sh
          cd ..

      # Install extra pip dependencies not in environment.yml
      - name: Install Extra Pip Dependencies
        run: |
          pip install --no-cache-dir \
            rouge-score==0.1.2 \
            evaluate==0.4.3 \
            datasets==3.0.1
          python -c "import nltk; nltk.download('wordnet')"

      # Run Pytest
      - name: Run Tests
        run: |
          pytest -v tests/
