name: Test SAGE with Pytest and Conda

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:  # ✅ 允许手动触发，并可以指定任意分支
jobs:
  test:
    name: Test SAGE
    runs-on: self-hosted
    strategy:
      max-parallel: 5

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Cache Conda Environment
      - name: Cache Conda Environment
        uses: actions/cache@v3
        with:
          path: |
            $HOME/miniconda3/envs/sage
            $HOME/.conda/envs/sage
            $HOME/.cache/pip
            $HOME/miniconda3/pkgs
            $HOME/.condarc
          key: ${{ runner.os }}-conda-${{ hashFiles('installation/env_setup/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-
        env:
          ACTIONS_STEP_DEBUG: true

      # Setup Miniconda and Python environment
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          python-version: "3.11"
          activate-environment: sage
          auto-activate-base: false

      # Use Deploy Key to Clone CANDY Repository
      - name: Configure SSH for Deploy Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CANDY_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Install Base Dependencies
      - name: Install Base Dependencies
        run: |
          mamba install -y python=3.11 pip
          mamba clean --all -y

      # Create or Update Conda Environment
      - name: Create or Update Environment
        run: |
          if conda env list | grep -q "sage"; then
            echo "Environment 'sage' already exists. Updating..."
            mamba env update --name sage --file installation/env_setup/environment.yml
          else
            echo "Creating environment 'sage'..."
            mamba env create --file installation/env_setup/environment.yml
          fi

      # Install Extra Pip Dependencies
      - name: Install Extra Pip Dependencies
        run: |
          conda run -n sage pip install --no-cache-dir \
            rouge-score==0.1.2 \
            evaluate==0.4.3 \
            datasets==3.0.1
          conda run -n sage python -c "import nltk; nltk.download('wordnet')"

      - name: Set up Hugging Face CLI
        run: |
          conda run -n sage huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      # Run Pytest
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          export SILICONCLOUD_API_KEY=${{ secrets.SILICONCLOUD_API_KEY }}
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export JINA_API_KEY=${{ secrets.JINA_API_KEY }}
          export ALIBABA_API_KEY=${{ secrets.ALIBABA_API_KEY }}
          conda run -n sage pytest -v sage_tests
