# .github/workflows/todo-to-issue-pr.yml
name: TODO-to-Issue (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  todo_to_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          INSERT_ISSUE_URLS: "true"
          # No commits:–– the action will use github.event.pull_request.diff_url
          # If you really want to override:
          # DIFF_URL: ${{ github.event.pull_request.diff_url }}

      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ $(git status --porcelain) ]]; then
            git commit -m "chore: add TODO issue links via todo-to-issue-action"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No TODO links to commit"
          fi
