name: TODO-to-Issue (PR)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  todo_to_issue:
    runs-on: self-hosted

    services:
      docker:
        image: docker:dind
        privileged: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 Git 历史

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          INSERT_ISSUE_URLS: "true"
          # ⚠️ Must be uppercase to match action.yml
          COMMITS: '["${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"]'
          # Force List-PR-Files API (avoid 406 on large diffs)
          DIFF_URL: ""

      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          if [[ $(git status --porcelain) ]]; then
            git commit -m "chore: add TODO issue links via todo-to-issue-action"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No TODO links to commit"
          fi
